TheNetworg/oauth2-azure

- README.md
- src/Provider/Azure.php
- src/Provider/AzureResourceOwner.php
I've updated this project to ensure the code meets the PSR 2 coding standards. It is important to note that the method signature for `getObjects` has changed. I've updated the signature, documentation and internal usage. Any consuming projects will need to be updated as well, as this will be a breaking change.
>Arguments with default values must be at the end of the argument list
I added PHPDoc blocks to the Resource Owner class. I would strongly urge you do the same to the Provider class. Also, adding some automated tests will help make sure the changes to your project are easily tracked as you move forward. 
Good luck.
> Add psr2 compliance

- README.md
For some reason we have to specify the 'resource' parameter in the request in order to access the graph API, so i've updated the doc so people won't spend hours trying to find why their token is not accepted.
> Update doc for resource parameter

- composer.json
firebase\php-jwt 3.0 and 4.0 are backwards compatible.
> Allow php-jwt 4.0

- src/Provider/Azure.php
I am trying to get oauth2-azure to work with the Azure AD 2.0 endpoint, and it works, apart from the fact that there is one feature I am missing: An override for the scope separator. 
```php
$provider = new \TheNetworg\OAuth2\Client\Provider\Azure([
'clientId' => ONEDRIVE_CLIENT_ID,
'clientSecret' => ONEDRIVE_SECRET,
'redirectUri' => WEB_ADDRESS . PATH_PREFIX . "/confirm/onedrive",
]);
$provider->urlAPI = "https://graph.microsoft.com/v1.0/";
$provider->resource = "https://graph.microsoft.com/";
$provider->pathAuthorize = "/oauth2/v2.0/authorize";
$provider->pathToken = "/oauth2/v2.0/token";
$provider->authWithResource = false;
$options = [
'scope' => ['https://graph.microsoft.com/User.Read', 'https://graph.microsoft.com/Files.Read.All', 'offline_access'],
'prompt' => 'consent',
]; …
```
> Added option to change scope separator

- src/Provider/Azure.php
This PR gets the v2.0.0 branch of oauth2-azure functioning and usable. I've broken it into commits to hopefully help check what I've done.
- 52bfdee
Corrects the response of `getOpenIdConfiguration()` and `getJwtVerificationKeys()` from an obect to an array. Addresses #55.
- 3fd3b0a
Adds `getScopeSeparator()` function so that scopes in an array are separated in the authorization url by spaces not commas.
- f3d4fe1
Fixes `validateToken()` so that the idToken is correctly decoded and verified by the firebase/jwt package. As improvements I removed the `nbf` and `exp` checks as firebase/jwt verifies theses already during the decode. Also added a new check that verifies the token issuer `iss` as it is recommended but firebase/jwt doesn't do it.
- The last commit is just to improve code styling …
> Branch v2.0.0 fixes

- README.md
While reading the documentation, came across an external link to a 404 page. Found the new URL for the page and updated accordingly.
> Fixes a broken link to "AD 2.0: Scopes not Resources" within the documentation

- src/Provider/Azure.php
This PR improves getJwtVerificationKeys in two ways:
* It uses chunk_split intead of wordwrap as [chunk_split](https://php.net/chunk_split) is made exactly for this purpose.
* It returns public keys instead of whole certificates as [openssl_verify](https://php.net/openssl_verify) is documented to expect keys (even it currently works with certificates as well).
> Improvements to getJwtVerificationKeys

- src/Provider/Azure.php
The `getTenantDetails` method harded the url rather than allowing
customization. This update utilizes the `urlLogin` parameter (which can
either be the legacy login.windows.net or login.microsoftonline.com),
introduces constants (as defined in PR #76) and then utilizes those to
build the URI to receive the openid-configuration data.
This will resolve issues with invalid issuer errors while creating the
`AccessToken` when utilizing the openid auth/token endpoints.
Fixes #78
> Provide better support for v2.0 OpenID Config

- src/Provider/Azure.php
Changed the function getLogoutUrl to have an empty default and return the url without "post_logout_redirect_uri" on empty.
Closes #95
> Make $post_logout_redirect_uri optional in getLogoutUrl()

- src/Provider/Azure.php
In case of a misconfiguration one does only get an "invalid_client" as messages which can be anything [regarding to Microsoft](https://github.com/Azure-Samples/active-directory-error-docs/wiki/invalid_client).
With the description in addition you can get helpful messages like:
```
invalid_client
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '12345678-1234-1234-1234-1234567890ab'.
Trace ID: 12345678-1234-1234-1234-1234567890ab
Correlation ID: 12345678-1234-1234-1234-1234567890ab
Timestamp: 2020-01-07 10:00:00Z
```
> Add error description to message to improve exception quality

- README.md
- src/Provider/Azure.php
- src/Token/AccessToken.php
Improve the library by:
- Adding support for v2.0 of AAD endpoints. The initial value is set via Azure::defaultEndPointVersion.
- Grabing most urls from an official /.well-known/openid-configuration endpoint instead of having them hard coded. 
- Resolved duplication of code in AccessToken::__construct and Azure::validateAccessToken.
- Added a helper method to retrieve Microsoft Graph root url from the /.well-known/openid-configuration endpoint.
Support for end points is not ideal as the underlying library does not provide necessary data when calling getBaseAuthorizationUrl, getBaseAccessTokenUrl etc. as the version should be determined by the token's `ver` value but the value nor the token is provided when calling these methods.
> Support endpoint v2.0

- src/Provider/Azure.php
Use correct claim based on token version to validate application ID.
- v1 token have application id in appid claim
- v2 token have application id in azp claim.
Doc: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#claims-in-access-tokens
> Remove app id validation

- README.md
- src/Provider/Azure.php
Hi,
We are using simplesamlphp module(https://github.com/cirrusidentity/simplesamlphp-module-authoauth2) with some oauth2-clients.
We want to use your client for AzureAD, but we need the possibility to set scopes and defaultEndPointVersion from the 'options' field in the constructor.
This PR allows setting the 'scopes' and  'defaultEndPointVersion' from the constructor.
Thanks for the review.
> Allow to set some params in list of options in constructor

- README.md
array_merge() expects scopes value in options to be an array
See: https://github.com/TheNetworg/oauth2-azure/blob/2649422a0dc74af32d21d9d738d37abcd5b03998/src/Provider/Azure.php#L47
> Fix: make scopes value an array

- composer.json
Allows firebase 6.x to be installed and fixes insecure encryption issue.
firebase/php-jwt@5.5.1 is vulnerable to Insecure Encryption due to an algorithm-confusion issue (e.g., RS256 / HS256) that exists via the kid (aka Key ID) header when multiple types of keys are loaded in a key ring. This allows an attacker to forge tokens that validate under the incorrect key.  This vulnerability is fixed in firebase/php-jwt@6.0.0.
> Firebase 6

- README.md
- src/Provider/Azure.php
> Add support for using a certificate instead of a shared secret

- src/Provider/Azure.php
AccessToken::getIdTokenClaims() can return null, but Azure::getRootMicrosoftGraphUri() expected an array. This caused `array_key_exists(): Argument #2 ($array) must be of type array, null given` error when the access token had no claims.
> Handle empty ID token claim

- .gitattributes
Dist archives fetched from composer using `--prefer-dist` are containing files that only usefull on dev environments.
Adding these git attributes will permit to remove them from dist archives.
> Exclude dev files from dist archives

- composer.json
- src/Provider/Azure.php
Microsoft's identity platform uses the kty parameter for the encryption family, alg is omitted. This PR gives the ability to set a defaultAlgorithm when `alg` is not included. 
Also passing in correct value to openssl_pkey_get_details() so it won't crash. 
Resolves #172
> Set default algorithm through config

- src/Provider/Azure.php
- src/Token/AccessToken.php
Remove unnecessary third argument when using \Firebase\JWT\JWT::decode , also incompatible with "firebase/php-jwt": "6.7.0"
> Fix compatibility with "firebase/php-jwt": "6.7.0"

- src/Provider/Azure.php
- tests/Fakers/B2cTokenFaker.php
Had a terrible Monday morning case of my local development VM missing NTP synchronization, spent 10 minutes figuring out why I was getting vague `The id_token is invalid!` errors all the time.
Improved error messages following Symfony standards: full grammatically correct sentences ending with a period, describing the real problem in detail including the most likely problem and solution.
The change at #369 repairs the broken tests on newer PHP versions (accessing a missing array value is a hard error now without null coalesce).
> Improve error messages
